/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-otp`; params?: Router.UnknownInputParams; } | { pathname: `/tailwind`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/admin-panel` | `/admin-panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-profile/edit` | `/my-profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-profile` | `/my-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/payment-failed` | `/payment-failed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/payment-successful` | `/payment-successful`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/theme.context`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/tailwind`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/admin-panel` | `/admin-panel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/my-profile/edit` | `/my-profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/my-profile` | `/my-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/payment-failed` | `/payment-failed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/payment-successful` | `/payment-successful`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/theme.context`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login-otp${`?${string}` | `#${string}` | ''}` | `/tailwind${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/admin-panel${`?${string}` | `#${string}` | ''}` | `/admin-panel${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/my-profile/edit${`?${string}` | `#${string}` | ''}` | `/my-profile/edit${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/my-profile${`?${string}` | `#${string}` | ''}` | `/my-profile${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/payment-failed${`?${string}` | `#${string}` | ''}` | `/payment-failed${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/payment-successful${`?${string}` | `#${string}` | ''}` | `/payment-successful${`?${string}` | `#${string}` | ''}` | `/hooks/theme.context${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-otp`; params?: Router.UnknownInputParams; } | { pathname: `/tailwind`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/admin-panel` | `/admin-panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-profile/edit` | `/my-profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/my-profile` | `/my-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/payment-failed` | `/payment-failed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/payment-successful` | `/payment-successful`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/theme.context`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
